# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kasey Lawrence - full-stack distraction
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Genomics resident for 10+ years. Next-Gen Sequencing E2E. I'm now carving a newer path
  focusing on data and software. Thoughts are my own. Other interests: Poison-Dart frogs,
  reef tanks, Raspberry Pi, video games, gardening, travelling, among too many other things 
  to list. Extremely happily married. Two wonderful children and a really fun life. Prone
  to negative emotion but I'm working on it!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kaseylawrence.com.com" # the base hostname & protocol for your site
twitter_username: pumilio
github_username:  kaseylawrence

# Build settings
markdown: kramdown
theme: architect